name: Build Waterbox

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  CC: clang-18
  CXX: clang++-18

jobs:

  # Build waterbox and cores
  build-waterbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
       submodules: recursive
    - name: Installing clang 18
      run: wget https://apt.llvm.org/llvm.sh;
           chmod u+x llvm.sh;
           sudo ./llvm.sh 18;
           clang-18 --version;
    - name: Building musl
      working-directory: ./waterbox/musl
      run: ./wbox_configure.sh;
           ./wbox_build.sh;
    - name: Building emulibc
      working-directory: ./waterbox/emulibc
      run: make
    - name: Building libco
      working-directory: ./waterbox/libco
      run: make
    - name: Building libcxx
      working-directory: ./waterbox/libcxx
      run: ./do-everything.sh
    - name: Building nyma
      working-directory: ./waterbox/nyma
      run: ./build-and-install-zlib.sh
    - name: Uploading compiled waterbox
      uses: actions/upload-artifact@v4
      with:
        name: compiled-waterbox
        path: |
          waterbox/libco/obj
          waterbox/musl/obj
          waterbox/emulibc/obj
          waterbox/libcxx/build*
          waterbox/sysroot

  build-gpgx:
    runs-on: ubuntu-latest
    needs: build-waterbox
    steps:
    - name: Download compiled waterbox
      uses: actions/download-artifact@v4
      with:
        name: compiled-waterbox
    - name: Building GPGX core
      working-directory: ./waterbox/gpgx
      run: make -j${nproc}