name: Build Waterbox

on:
  pull_request:
    #branches: [ "master" ]
  push:
    #branches: [ "master" ]
    branches: [ "upstreamCI" ]

env:
  CC: clang-15
  CXX: clang++-15

jobs:

  # Build waterbox and cores
  build-waterbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Getting submodule(s)
      working-directory: ./waterbox/
      run: git submodule init musl;
           git submodule update musl
    - name: Building musl
      working-directory: ./waterbox/musl
      run: ./wbox_configure.sh;
           ./wbox_build.sh;
    - name: Building emulibc
      working-directory: ./waterbox/emulibc
      run: make
    - name: Building libco
      working-directory: ./waterbox/libco
      run: make
    - name: Building libcxx
      working-directory: ./waterbox/libcxx
      run: ./do-everything.sh
    - name: Building nyma
      working-directory: ./waterbox/nyma
      run: ./build-and-install-zlib.sh
    - name: Uploading compiled waterbox
      uses: actions/upload-artifact@v4
      with:
        name: compiled-waterbox
        path: |
          waterbox/libco/obj
          waterbox/musl/obj
          waterbox/emulibc/obj
          waterbox/libcxx/build*
          waterbox/sysroot

  build-gpgx:
    runs-on: ubuntu-latest
    needs: build-waterbox
    steps:
    - uses: actions/checkout@v4
    - name: Download compiled waterbox
      uses: actions/download-artifact@v4
      with:
        name: compiled-waterbox
    - name: Listing Files
      working-directory: ./waterbox/sysroot
      run: ls -laR
    - name: Getting submodule(s)
      working-directory: ./waterbox/gpgx
      run: git submodule init Genesis-Plus-GX;
           git submodule update Genesis-Plus-GX
    - name: Building GPGX core
      working-directory: ./waterbox/gpgx
      run: make -j${nproc}