name: Build Emulation Cores

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  CC: clang-18
  CXX: clang++-18

jobs:

  build-waterbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installing clang 18
      run: wget https://apt.llvm.org/llvm.sh;
          chmod u+x llvm.sh;
          sudo ./llvm.sh 18;
          clang-18 --version;    
    - name: Getting submodule(s)
      working-directory: ./waterbox/
      run: git submodule update --init musl
    - name: Building musl
      working-directory: ./waterbox/musl
      run: ./wbox_configure.sh;
           ./wbox_build.sh;
    - name: Building emulibc
      working-directory: ./waterbox/emulibc
      run: make
    - name: Building libco
      working-directory: ./waterbox/libco
      run: make
    - name: Building libcxx
      working-directory: ./waterbox/libcxx
      run: ./do-everything.sh
    - name: Building nyma
      working-directory: ./waterbox/nyma
      run: ./build-and-install-zlib.sh
    - name: Uploading compiled waterbox
      uses: actions/upload-artifact@v4
      with:
        name: compiled-waterbox
        path: |
          waterbox/libco
          waterbox/musl
          waterbox/libcxx
          waterbox/sysroot
  
  build-waterboxed-cores:
    runs-on: ubuntu-latest
    needs: build-waterbox
    steps:
    - uses: actions/checkout@v4
    - name: Getting submodule(s)
      working-directory: ./waterbox/
      run: git submodule update --init snes9x;
           git submodule update --init melon/melonDS;
           git submodule update --init nyma/mednafen;
           git submodule update --init ares64/ares/thirdparty/angrylion-rdp;
           git submodule update --init gpgx/Genesis-Plus-GX;
    - name: Download compiled waterbox
      uses: actions/download-artifact@v4
      with:
        name: compiled-waterbox
        path: waterbox
    - name: Installing clang 18
      run: wget https://apt.llvm.org/llvm.sh;
            chmod u+x llvm.sh;
            sudo ./llvm.sh 18;
            clang-18 --version;        
    - name: Giving execution permission to compiler
      working-directory: ./waterbox/sysroot
      run: chmod u+x bin/*
    - name: Building cores
      working-directory: ./waterbox/
      run: ./make-all-cores.sh

  build-mame:
        runs-on: ubuntu-latest
        needs: build-waterbox
        steps:
        - uses: actions/checkout@v4
        - name: Getting submodule(s)
          working-directory: ./waterbox/
          run: git submodule update --init mame-arcade/mame
        - name: Download compiled waterbox
          uses: actions/download-artifact@v4
          with:
            name: compiled-waterbox
            path: waterbox
        - name: Installing clang 18
          run: wget https://apt.llvm.org/llvm.sh;
                chmod u+x llvm.sh;
                sudo ./llvm.sh 18;
                clang-18 --version;        
        - name: Giving execution permission to compiler
          working-directory: ./waterbox/sysroot
          run: chmod u+x bin/*
        - name: Building MAME
          working-directory: ./waterbox/mame-arcade
          run: make -j4

  build-quickernes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Getting submodule(s)
      working-directory: ./quicknes
      run: git submodule update --recursive --init core
    - name: Building QuickerNES core (Linux)
      working-directory: ./quicknes/make
      run: make -j4
